# NORMALIZATION PROBLEM

In [7]:
import numpy as np

#Generate the initial random array of size 5x5

x = np.random.random((5,5))

#Get the Mean and standard deviation using .mean and .std
x_mean = x.mean()
x_std = x.std()

#calculate for the normalized array

x_normalized = ((x - x_mean)/x_std)

# Save to .npy file
np.save('x_normalized.npy', x_normalized)

In [9]:
z = np.load("x_normalized.npy")
print(z)

[[ 0.6142165   0.45706555 -0.83336743 -1.71131259  1.74404781]
 [ 1.66505532  1.00476596 -1.39577854 -1.19293716  1.49561821]
 [ 0.27731653 -0.52277305 -1.41799089 -0.94368246  0.39948121]
 [-0.44352286 -0.47852622 -0.78301     0.294615   -0.31485084]
 [-0.3815356   1.19339625  0.44905929 -0.48536872  1.31001872]]


# DIVISIBLE BY 3 PROBLEM

In [24]:
import numpy as np

#generate a 10 x 10 nd Array

intarray = np.arange(1, 101) ** 2

for x in intarray:
    divisible = intarray[intarray % 3 == 0]
    
print(divisible)

#save as .npy

np.save("div_by_3.npy", divisible)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [25]:
v = np.load("div_by_3.npy")
print(v)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
